# Generated by Django 6.0.5 on 2026-05-22 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoumissionExercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_reponse', models.FileField(upload_to='soumissions_exercices/')),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travaux_rendus', to='api.etudiant')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions', to='api.exercice')),
            ],
            options={
                'unique_together': {('exercice', 'etudiant')},
            },
        ),
    ]
